export type Modifier = { name: string; ratio: number; category: string };

export const MAX_POWER_BIT = 40;
export const BAKE_IN_MAX = 16;

export const STANDARD_SEA_MODS = [
  "Agility", "Block Value", "Camouflage", "Constitution",
  "Luck", "Precision", "Stamina", "Strength",
];

export const MODIFIERS: Modifier[] = [
  // ── Combat: Offense ──────────────────────────────────────────────────────
  { name: "Combat Offense: Strikethrough Value",       ratio: 4,  category: "Combat: Offense" },
  { name: "Creature Critical Chance",                  ratio: 10, category: "Combat: Offense" },
  { name: "Critical Chance Increase",                  ratio: 15, category: "Combat: Offense" },
  { name: "Detect Camouflage",                         ratio: 3,  category: "Combat: Offense" },
  { name: "Dodge Reduction",                           ratio: 8,  category: "Combat: Offense" },
  { name: "Droid Critical Chance",                     ratio: 10, category: "Combat: Offense" },
  { name: "Humanoid Critical Chance",                  ratio: 10, category: "Combat: Offense" },
  { name: "Parry Reduction",                           ratio: 6,  category: "Combat: Offense" },
  { name: "PvP Critical Chance",                       ratio: 10, category: "Combat: Offense" },
  { name: "Strikethrough Chance",                      ratio: 6,  category: "Combat: Offense" },
  { name: "Weapon Damage",                             ratio: 10, category: "Combat: Offense" },
  { name: "DOT Damage",                                ratio: 10, category: "Combat: Offense" },
  { name: "AOE Damage",                                ratio: 10, category: "Combat: Offense" },

  // ── Combat: Defense ──────────────────────────────────────────────────────
  { name: "Bleeding Absorption",                       ratio: 4,  category: "Combat: Defense" },
  { name: "Bleeding Resistance",                       ratio: 4,  category: "Combat: Defense" },
  { name: "Block Chance",                              ratio: 4,  category: "Combat: Defense" },
  { name: "Block Value",                               ratio: 1,  category: "Combat: Defense" },
  { name: "Critical Hit Reduction",                    ratio: 4,  category: "Combat: Defense" },
  { name: "Disease Absorption",                        ratio: 4,  category: "Combat: Defense" },
  { name: "Disease Resistance",                        ratio: 4,  category: "Combat: Defense" },
  { name: "Dodge Chance",                              ratio: 8,  category: "Combat: Defense" },
  { name: "Evasion Chance",                            ratio: 3,  category: "Combat: Defense" },
  { name: "Evasion Value",                             ratio: 4,  category: "Combat: Defense" },
  { name: "Fire Absorption",                           ratio: 4,  category: "Combat: Defense" },
  { name: "Fire Resistance",                           ratio: 4,  category: "Combat: Defense" },
  { name: "Glancing Blow Increase",                    ratio: 18, category: "Combat: Defense" },
  { name: "Glancing Blow Increase (Melee)",            ratio: 14, category: "Combat: Defense" },
  { name: "Glancing Blow Increase (Ranged)",           ratio: 14, category: "Combat: Defense" },
  { name: "Healing Potency",                           ratio: 8,  category: "Combat: Defense" },
  { name: "Parry Rating",                              ratio: 6,  category: "Combat: Defense" },
  { name: "Poison Absorption",                         ratio: 4,  category: "Combat: Defense" },
  { name: "Poison Resistance",                         ratio: 4,  category: "Combat: Defense" },

  // ── Combat: Profession Specific ──────────────────────────────────────────
  { name: "Assassinate Action Cost",                   ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assassinate Critical Chance",               ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assassinate Damage",                        ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assassinate Freeshot Chance",               ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assault Action Cost",                       ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assault Critical Chance",                   ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assault Damage",                            ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Assault Freeshot Chance",                   ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Camouflage",                                ratio: 1,  category: "Combat: Profession Specific" },
  { name: "Droid Speed",                               ratio: 3,  category: "Combat: Profession Specific" },
  { name: "Fast Draw Critical Chance",                 ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Fast Draw Damage",                          ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Fast Draw/Precision Strike Action Cost",    ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Fast Draw/Precision Strike Freeshot Chance",ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Focused Fire Action",                       ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Focused Fire Critical Chance",              ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Focused Fire Damage",                       ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Focused Fire Freeshot Chance",              ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Heal Action Cost Reduction",                ratio: 10, category: "Combat: Profession Specific" },
  { name: "Sure Shot Action Cost",                     ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Sure Shot Critical Chance",                 ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Sure Shot Damage",                          ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Sure Shot Freeshot Chance",                 ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Tracking Droids",                           ratio: 4,  category: "Combat: Profession Specific" },
  { name: "Vital Strike Action Cost",                  ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Vital Strike Critical Chance",              ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Vital Strike Damage",                       ratio: 8,  category: "Combat: Profession Specific" },
  { name: "Vital Strike Freeshot Chance",              ratio: 8,  category: "Combat: Profession Specific" },

  // ── Combat: Weapon Specific ──────────────────────────────────────────────
  { name: "1-H Critical Chance",                       ratio: 10, category: "Combat: Weapon Specific" },
  { name: "1-Handed Melee Damage",                     ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Carbine Action Cost",                       ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Carbine Critical Chance",                   ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Carbine Damage",                            ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Heavy Weapon Action Cost",                  ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Heavy Weapon Critical Chance",              ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Heavy Weapon Damage",                       ratio: 14, category: "Combat: Weapon Specific" },
  { name: "One-Hand Melee Action Cost",                ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Pistol Action Cost",                        ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Pistol Critical Chance",                    ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Pistol Damage",                             ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Polearm Action Cost",                       ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Polearm Critical Chance",                   ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Polearm Damage",                            ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Rifle Action Cost",                         ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Rifle Critical Chance",                     ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Rifle Damage",                              ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Two-Hand Melee Action Cost",                ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Two-Hand Melee Critical Chance",            ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Two-Hand Melee Damage",                     ratio: 14, category: "Combat: Weapon Specific" },
  { name: "Unarmed Action Cost",                       ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Unarmed Critical Chance",                   ratio: 10, category: "Combat: Weapon Specific" },
  { name: "Unarmed Damage",                            ratio: 14, category: "Combat: Weapon Specific" },

  // ── Core Stats ───────────────────────────────────────────────────────────
  { name: "Agility",                                   ratio: 1,  category: "Core Stats" },
  { name: "Constitution",                              ratio: 1,  category: "Core Stats" },
  { name: "Luck",                                      ratio: 1,  category: "Core Stats" },
  { name: "Precision",                                 ratio: 1,  category: "Core Stats" },
  { name: "Stamina",                                   ratio: 1,  category: "Core Stats" },
  { name: "Strength",                                  ratio: 1,  category: "Core Stats" },

  // ── Elemental Penetration ────────────────────────────────────────────────
  { name: "Elemental Penetration: Acid",               ratio: 10, category: "Elemental Penetration" },
  { name: "Elemental Penetration: Cold",               ratio: 10, category: "Elemental Penetration" },
  { name: "Elemental Penetration: Electricity",        ratio: 10, category: "Elemental Penetration" },
  { name: "Elemental Penetration: Heat",               ratio: 10, category: "Elemental Penetration" },

  // ── Profession: Commando ─────────────────────────────────────────────────
  { name: "Devastation",                               ratio: 15, category: "Profession: Commando" },

  // ── Profession: Entertainer ──────────────────────────────────────────────
  { name: "Dance Knowledge",                           ratio: 3,  category: "Profession: Entertainer" },
  { name: "Dance Prop Assembly",                       ratio: 3,  category: "Profession: Entertainer" },
  { name: "Dancing Enhancement",                       ratio: 3,  category: "Profession: Entertainer" },
  { name: "Instrument Assembly",                       ratio: 3,  category: "Profession: Entertainer" },
  { name: "Music Knowledge",                           ratio: 3,  category: "Profession: Entertainer" },
  { name: "Musical Enhancement",                       ratio: 3,  category: "Profession: Entertainer" },

  // ── Profession: Grenadier ────────────────────────────────────────────────
  { name: "Grenade Damage",                            ratio: 14, category: "Profession: Grenadier" },
  { name: "Grenade Action Cost",                       ratio: 10, category: "Profession: Grenadier" },
  { name: "Grenade Crit Chance",                       ratio: 10, category: "Profession: Grenadier" },

  // ── Profession: Jedi ─────────────────────────────────────────────────────
  { name: "Jedi Strike Action Cost",                   ratio: 8,  category: "Profession: Jedi" },
  { name: "Jedi Strike Critical Chance",               ratio: 8,  category: "Profession: Jedi" },
  { name: "Jedi Strike Freeshot Chance",               ratio: 8,  category: "Profession: Jedi" },
  { name: "Lightsaber Assembly",                       ratio: 3,  category: "Profession: Jedi" },
  { name: "Lightsaber Experimentation",                ratio: 5,  category: "Profession: Jedi" },
  { name: "One-Hand Lightsaber Damage",                ratio: 14, category: "Profession: Jedi" },
  { name: "One-Handed Lightsaber Action Cost",         ratio: 10, category: "Profession: Jedi" },
  { name: "Polearm Lightsaber Action Cost",            ratio: 10, category: "Profession: Jedi" },
  { name: "Polearm Lightsaber Damage",                 ratio: 14, category: "Profession: Jedi" },
  { name: "Strike Damage",                             ratio: 8,  category: "Profession: Jedi" },
  { name: "Two-Hand Lightsaber Action Cost",           ratio: 10, category: "Profession: Jedi" },
  { name: "Two-Hand Lightsaber Damage",                ratio: 14, category: "Profession: Jedi" },
  { name: "Saber Burst Damage",                        ratio: 8,  category: "Profession: Jedi" },
  { name: "Jedi Strike Damage",                        ratio: 8,  category: "Profession: Jedi" },
  { name: "Force Lightning Damage",                    ratio: 8,  category: "Profession: Jedi" },
  { name: "Jedi Sweep Damage",                         ratio: 8,  category: "Profession: Jedi" },

  // ── Profession: Shipwright ───────────────────────────────────────────────
  { name: "Advanced Assembly",                         ratio: 3,  category: "Profession: Shipwright" },
  { name: "Advanced Component Experimentation",        ratio: 4,  category: "Profession: Shipwright" },
  { name: "Booster Assembly",                          ratio: 3,  category: "Profession: Shipwright" },
  { name: "Booster Experimentation",                   ratio: 4,  category: "Profession: Shipwright" },
  { name: "Chassis Assembly",                          ratio: 3,  category: "Profession: Shipwright" },
  { name: "Chassis Experimentation",                   ratio: 4,  category: "Profession: Shipwright" },
  { name: "Engine Assembly",                           ratio: 3,  category: "Profession: Shipwright" },
  { name: "Engine Experimentation",                    ratio: 4,  category: "Profession: Shipwright" },
  { name: "Power Systems Assembly",                    ratio: 3,  category: "Profession: Shipwright" },
  { name: "Power Systems Experimentation",             ratio: 4,  category: "Profession: Shipwright" },
  { name: "Shield Experimentation",                    ratio: 4,  category: "Profession: Shipwright" },
  { name: "Shields Assembly",                          ratio: 3,  category: "Profession: Shipwright" },
  { name: "Weapon Systems",                            ratio: 3,  category: "Profession: Shipwright" },
  { name: "Weapon Systems Experimentation",            ratio: 4,  category: "Profession: Shipwright" },

  // ── Profession: Trader ───────────────────────────────────────────────────
  { name: "Armor Assembly",                            ratio: 3,  category: "Profession: Trader" },
  { name: "Armor Experimentation",                     ratio: 4,  category: "Profession: Trader" },
  { name: "Artisan Assembly",                          ratio: 3,  category: "Profession: Trader" },
  { name: "Artisan Experimentation",                   ratio: 4,  category: "Profession: Trader" },
  { name: "Clothing Assembly",                         ratio: 3,  category: "Profession: Trader" },
  { name: "Clothing Experimentation",                  ratio: 4,  category: "Profession: Trader" },
  { name: "Cybernetic Assembly",                       ratio: 3,  category: "Profession: Trader" },
  { name: "Cybernetic Experimentation",                ratio: 4,  category: "Profession: Trader" },
  { name: "Droid Assembly",                            ratio: 3,  category: "Profession: Trader" },
  { name: "Droid Experimentation",                     ratio: 4,  category: "Profession: Trader" },
  { name: "Food Assembly",                             ratio: 3,  category: "Profession: Trader" },
  { name: "Food Experimentation",                      ratio: 4,  category: "Profession: Trader" },
  { name: "Reverse Engineering Chance",                ratio: 10, category: "Profession: Trader" },
  { name: "Structure Assembly",                        ratio: 3,  category: "Profession: Trader" },
  { name: "Structure Experimentation",                 ratio: 4,  category: "Profession: Trader" },
  { name: "Weapon Assembly",                           ratio: 3,  category: "Profession: Trader" },
  { name: "Weapon Experimentation",                    ratio: 4,  category: "Profession: Trader" },
];

export const CATEGORY_COLORS: Record<string, string> = {
  "Combat: Offense":            "#c84040",
  "Combat: Defense":            "#4a88c8",
  "Combat: Profession Specific":"#c8a040",
  "Combat: Weapon Specific":    "#d06848",
  "Core Stats":                 "#a0c870",
  "Elemental Penetration":      "#40c8b8",
  "Beast Master":               "#40aa60",
  "Profession: Commando":       "#cc6633",
  "Profession: Grenadier":      "#c8802a",
  "Profession: Entertainer":    "#c060c0",
  "Profession: Jedi":           "#8060e0",
  "Profession: Shipwright":     "#6090c0",
  "Profession: Trader":         "#80a040",
};
